### ISSUE TITLE
Bug Fix |

### ISSUE THREAD

**Issue by Deepak91168** [Deepak91168/VisualizeSorting#3]
Irrelevant Rectangular Box.
The Empty Read Rectangle is not necessary it is used to show algo. time. Try to implement different logic to calculate algo. time or fix existing one.

![Screenshot from 2022-10-20 21-03-02](https://user-images.githubusercontent.com/78257493/196993283-38f1dafb-c976-4480-8beb-c7990b1e7cb4.png)

**Comment by harsh0620** [comment]
Hey @Deepak91168 , Please assign me this task.

**Comment by Siya8een** [comment]
assign this to me @Deepak91168  sir
