### ISSUE TITLE
Add Gifs 

### ISSUE THREAD

**Issue by Deepak91168** [Deepak91168/VisualizeSorting#7]
Add two-three gifs in documentation in which the demonstration of the project is clear....
Selecting Algo -> choosing size -> Running of Algo

**Comment by srijoy-paul** [comment]
Hey can you assign me this task? @Deepak91168

**Comment by srijoy-paul** [comment]
Hey @Deepak91168 Please Check the PR and merge it

**Comment by srijoy-paul** [comment]
Will be accepting the PR before today end of the day?
I want it to be counted for hactoberfest
@Deepak91168

**Comment by Deepak91168** [comment]
Thanks for Contributing :)
